name: Build & Deploy GHDB

on:
  push:
    branches: [ prod ]


jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Deploy GHDB
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          port: 22

          script: |
            cd Projects/ghdb/
            git pull
            bash ./scripts/init_crawler.sh
            echo "[SUCCESS] Deployed GHDB!"
